# Generated by Django 6.0.5 on 2026-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_add_tourist_attractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
