# Generated by Django 6.0.5 on 2026-05-13 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_alter_touristattraction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('guesthouse', 'Guesthouse'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('camp', 'Camp'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('price_per_night', models.IntegerField()),
                ('max_guests', models.IntegerField(default=2)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodation_images/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
