# Generated by Django 6.0.5 on 2026-05-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_alter_contactmessage_id_alter_feedback_id'),
        ('tourism', '0010_set_placeholder_images'),
    ]

    operations = [
    ]
