# Generated by Django 6.0.5 on 2026-05-15 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('matatu', 'Matatu'), ('taxi', 'Taxi'), ('car_rental', 'Car Rental'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('boat', 'Boat'), ('ferry', 'Ferry'), ('train', 'Train'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='Base location or route', max_length=100)),
                ('destination', models.CharField(blank=True, help_text='If applicable', max_length=100)),
                ('price_per_trip', models.IntegerField(help_text='Price per trip or per hour')),
                ('price_unit', models.CharField(default='trip', help_text='e.g., trip, hour, day', max_length=20)),
                ('capacity', models.IntegerField(default=1, help_text='Number of passengers')),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities')),
                ('image', models.ImageField(blank=True, null=True, upload_to='transport_images/')),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('available_24_7', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
