# Generated by Django 6.0.5 on 2026-05-15 08:35

from django.db import migrations


def create_sample_transports(apps, schema_editor):
    Transport = apps.get_model('tourism', 'Transport')
    samples = [
        {
            'name': 'Diani Matatu Service',
            'transport_type': 'matatu',
            'description': 'Reliable matatu service connecting Diani Beach to Mombasa city center. Comfortable seating with AC available on premium routes.',
            'location': 'Diani Beach',
            'destination': 'Mombasa CBD',
            'price_per_trip': 150,
            'price_unit': 'trip',
            'capacity': 14,
            'amenities': 'AC, Music, Luggage space',
            'contact_info': '+254 712 345 678',
            'available_24_7': False,
            'latitude': -4.3000,
            'longitude': 39.5833,
        },
        {
            'name': 'Mombasa Airport Taxi',
            'transport_type': 'taxi',
            'description': 'Professional taxi service from Moi International Airport to all coastal destinations. Meet and greet service available.',
            'location': 'Moi International Airport',
            'destination': 'Coastal destinations',
            'price_per_trip': 2500,
            'price_unit': 'trip',
            'capacity': 4,
            'amenities': 'AC, WiFi, Water, Professional driver',
            'contact_info': '+254 722 123 456',
            'available_24_7': True,
            'latitude': -4.0349,
            'longitude': 39.5942,
        },
        {
            'name': 'Coast Bus Services',
            'transport_type': 'bus',
            'description': 'Modern bus service connecting major coastal towns. Comfortable seats, entertainment system, and onboard refreshments.',
            'location': 'Mombasa',
            'destination': 'Malindi',
            'price_per_trip': 800,
            'price_unit': 'trip',
            'capacity': 50,
            'amenities': 'AC, TV, Refreshments, WiFi',
            'contact_info': '+254 733 987 654',
            'available_24_7': False,
            'latitude': -4.0434,
            'longitude': 39.6525,
        },
        {
            'name': 'Diani Beach Bicycle Rental',
            'transport_type': 'bicycle',
            'description': 'Quality bicycle rental for exploring Diani Beach and surrounding areas. Various bike types available including mountain bikes and cruisers.',
            'location': 'Diani Beach',
            'price_per_trip': 300,
            'price_unit': 'day',
            'capacity': 1,
            'amenities': 'Helmet, Lock, Basket',
            'contact_info': '+254 711 567 890',
            'available_24_7': False,
            'latitude': -4.3000,
            'longitude': 39.5833,
        },
        {
            'name': 'Kilifi Boat Charter',
            'transport_type': 'boat',
            'description': 'Private boat charters for fishing trips, island hopping, and coastal exploration. Experienced captains and safety equipment included.',
            'location': 'Kilifi Creek',
            'price_per_trip': 5000,
            'price_unit': 'day',
            'capacity': 8,
            'amenities': 'Life jackets, Fishing gear, Cooler, GPS',
            'contact_info': '+254 744 321 098',
            'available_24_7': False,
            'latitude': -3.6300,
            'longitude': 39.8500,
        },
    ]
    for sample in samples:
        Transport.objects.get_or_create(name=sample['name'], defaults=sample)


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_transport'),
    ]

    operations = [
        migrations.RunPython(create_sample_transports),
    ]
